### ISSUE TITLE
Missing "How to use" instructions

### ISSUE THREAD

**Issue by hydrocat** [stonewell/pymterm#1]
I am trying to run pymterm but I didn't find any instructions on how to install/use it. I am on Linux and **setup.py** complains about the platform (It seems to want to build a mac's "app"). Running **pymterm.py**  by itself yields the error:

> $ python pymterm.py
> ERROR:root:load configuration failed
> Traceback (most recent call last):
>  File "pymterm/pymterm.py", line 43, in pymterm_main cfg = session_config.SessionConfig(args)
>  File "/home/hydrocat/Downloads/git/pymterm/pymterm/session_config.py", line 39, in __init__ self.load_config()
>  File "/home/hydrocat/Downloads/git/pymterm/pymterm/session_config.py", line 185, in load_config self.config = json.load(f)
> File "/usr/lib/python2.7/json/__init__.py", line 290, in load **kw)
> File "/usr/lib/python2.7/json/__init__.py", line 338, in loads return _default_decoder.decode(s)
>  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode obj, end = self.scan_once(s, idx)
> ValueError: Expecting , delimiter: line 18 column 6 (char 301)
> usage: (usage omitted)

**Comment by stonewell** [comment]
Update the documents, please try again follow the documents to install/setup/run

## Install & Setup & Run
 - [How to install pymterm on Linux/Mac/Windows](../docs/install.md)
 - [How to setup pymterm](../docs/setup.md)
 - [How to use pymterm](../docs/usage.md)
